### ISSUE TITLE
Too many keys in db

### ISSUE THREAD

**Issue by abdel-ke** [appetism/ops-backend#3]
ops-backend-dev  | error: Failed to sync DB Too many keys specified; max 64 keys allowed

**Comment by ouarrtaha** [comment]
fixed in this https://github.com/appetism/ops-backend/commit/adad514693e390474a666f7f59efac5f604770fd

please alter ur local db and remove all indexes, and relaunch the app again to resync,
---
we won't be using  sequelizeConnection.sync({alter: true}) in dev as it recreate indexes every run, so any upcoming changes to db please use migrations
